CREATE TABLE IF NOT EXISTS FCF_DOMAIN (
	ID VARCHAR(20) PRIMARY KEY,
	NAME VARCHAR(255),
	ATTRIBUTES CLOB DEFAULT '');

MERGE INTO FCF_DOMAIN (ID, NAME, ATTRIBUTES) KEY(ID) VALUES
	('1', 'General Medicine Clinic', 'LOGIN.LOGO=images/gmc.png'),
	('2', 'Emergency Room', 'LOGIN.LOGO=images/er.png'),
	('3', 'Test Hospital', 'default=true;LOGIN.LOGO=images/hospital.png'),
	('*', 'All Domains', '');

CREATE TABLE IF NOT EXISTS FCF_USER (
	ID VARCHAR(20) PRIMARY KEY,
	USERNAME VARCHAR(40),
	PASSWORD VARCHAR(40),
	NAME VARCHAR(255),
	DOMAIN VARCHAR(20),
	AUTHORITIES CLOB DEFAULT '');

MERGE INTO FCF_USER (ID, USERNAME, PASSWORD, NAME, DOMAIN, AUTHORITIES) KEY(ID) VALUES
	('1', 'doctor', 'doctor', 'Doctor, Test', '1', 'PRIV_PATIENT_SELECT'),
	('2', 'demo', 'demo', 'User, Test', '*', 'PRIV_DEBUG,PRIV_FCF_DESIGNER,PRIV_PATIENT_SELECT');
	
